# Project: øŒ…Ëdevcpp
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ast.o lex.o main.o parser.o
LINKOBJ  = ast.o lex.o main.o parser.o
LIBS     = -L"D:/Dev-cpp/MinGW64/lib" -L"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-cpp/MinGW64/include" -I"D:/Dev-cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = øŒ…Ëdevcpp.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c99
CFLAGS   = $(INCS) -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ast.o: ast.c
	$(CC) -c ast.c -o ast.o $(CFLAGS)

lex.o: lex.c
	$(CC) -c lex.c -o lex.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

parser.o: parser.c
	$(CC) -c parser.c -o parser.o $(CFLAGS)
